spring:
  application:
    name: departement
    
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: dkassa
    password: Mysql515
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    
  config:
    
    import: optional:ConfigServer:http://localhost:8181
    
    
     
        
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


    
   
server:
  port: 8086
  
  
  
